use crate::common::file_reader::ProcFileReader;
use crate::common::parser_utils::parse_u64_swar;
use crate::common::procfs_constants::PROC_FS_ROOT_PATH;
use std::collections::HashMap;
use std::path::Path;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::thread;
use std::thread::JoinHandle;

/*
Field Number
Field 1 - Float
    1-Minute Load Average
    The average number of scheduling entities (processes/threads) that were either executable (State R)
    or blocked waiting for disk I/O (State D) over the last minute.
Field 2 - Float
    5-Minute Load Average
    The same workload metric averaged over the last 5 minutes.
Field 3 - Float
    15-Minute Load Average
    The same workload metric averaged over the last 15 minutes.
Field 4 - int32/int32
    Runnable / Total Entities
    Consists of two numbers separated by a slash (/):
    Numerator: The number of kernel scheduling entities currently executable and waiting to run.
    Denominator: The total number of kernel scheduling entities that currently exist on the system.
Field 5 - int32
    Last Created PID
    The Process ID (PID) of the most recently allocated process or thread on the system.
 */

pub struct ProcFSVmStatReader {
    reader: ProcFileReader<16384>,
    values: ProcVmStatFields,
}

#[derive(Debug, Default, Clone, Copy)]
pub struct ProcVmStatFields {
    pub nr_free_pages: u64,
    pub nr_free_pages_blocks: u64,
    pub nr_zone_inactive_anon: u64,
    pub nr_zone_active_anon: u64,
    pub nr_zone_inactive_file: u64,
    pub nr_zone_active_file: u64,
    pub nr_zone_unevictable: u64,
    pub nr_zone_write_pending: u64,
    pub nr_mlock: u64,
    pub nr_zspages: u64,
    pub nr_free_cma: u64,
    pub nr_unaccepted: u64,
    pub numa_hit: u64,
    pub numa_miss: u64,
    pub numa_foreign: u64,
    pub numa_interleave: u64,
    pub numa_local: u64,
    pub numa_other: u64,
    pub nr_inactive_anon: u64,
    pub nr_active_anon: u64,
    pub nr_inactive_file: u64,
    pub nr_active_file: u64,
    pub nr_unevictable: u64,
    pub nr_slab_reclaimable: u64,
    pub nr_slab_unreclaimable: u64,
    pub nr_isolated_anon: u64,
    pub nr_isolated_file: u64,
    pub workingset_nodes: u64,
    pub workingset_refault_anon: u64,
    pub workingset_refault_file: u64,
    pub workingset_activate_anon: u64,
    pub workingset_activate_file: u64,
    pub workingset_restore_anon: u64,
    pub workingset_restore_file: u64,
    pub workingset_nodereclaim: u64,
    pub nr_anon_pages: u64,
    pub nr_mapped: u64,
    pub nr_file_pages: u64,
    pub nr_dirty: u64,
    pub nr_writeback: u64,
    pub nr_shmem: u64,
    pub nr_shmem_hugepages: u64,
    pub nr_shmem_pmdmapped: u64,
    pub nr_file_hugepages: u64,
    pub nr_file_pmdmapped: u64,
    pub nr_anon_transparent_hugepages: u64,
    pub nr_vmscan_write: u64,
    pub nr_vmscan_immediate_reclaim: u64,
    pub nr_dirtied: u64,
    pub nr_written: u64,
    pub nr_throttled_written: u64,
    pub nr_kernel_misc_reclaimable: u64,
    pub nr_foll_pin_acquired: u64,
    pub nr_foll_pin_released: u64,
    pub nr_vmalloc: u64,
    pub nr_kernel_stack: u64,
    pub nr_page_table_pages: u64,
    pub nr_sec_page_table_pages: u64,
    pub nr_iommu_pages: u64,
    pub nr_swapcached: u64,
    pub pgpromote_success: u64,
    pub pgpromote_candidate: u64,
    pub pgpromote_candidate_nrl: u64,
    pub pgdemote_kswapd: u64,
    pub pgdemote_direct: u64,
    pub pgdemote_khugepaged: u64,
    pub pgdemote_proactive: u64,
    pub pgsteal_kswapd: u64,
    pub pgsteal_direct: u64,
    pub pgsteal_khugepaged: u64,
    pub pgsteal_proactive: u64,
    pub pgsteal_anon: u64,
    pub pgsteal_file: u64,
    pub pgscan_kswapd: u64,
    pub pgscan_direct: u64,
    pub pgscan_khugepaged: u64,
    pub pgscan_proactive: u64,
    pub pgscan_anon: u64,
    pub pgscan_file: u64,
    pub pgrefill: u64,
    pub nr_hugetlb: u64,
    pub nr_balloon_pages: u64,
    pub nr_kernel_file_pages: u64,
    pub nr_gpu_active: u64,
    pub nr_gpu_reclaim: u64,
    pub nr_dirty_threshold: u64,
    pub nr_dirty_background_threshold: u64,
    pub nr_memmap_pages: u64,
    pub nr_memmap_boot_pages: u64,
    pub pgpgin: u64,
    pub pgpgout: u64,
    pub pswpin: u64,
    pub pswpout: u64,
    pub pgalloc_dma: u64,
    pub pgalloc_dma32: u64,
    pub pgalloc_normal: u64,
    pub pgalloc_movable: u64,
    pub pgalloc_device: u64,
    pub allocstall_dma: u64,
    pub allocstall_dma32: u64,
    pub allocstall_normal: u64,
    pub allocstall_movable: u64,
    pub allocstall_device: u64,
    pub pgskip_dma: u64,
    pub pgskip_dma32: u64,
    pub pgskip_normal: u64,
    pub pgskip_movable: u64,
    pub pgskip_device: u64,
    pub pgfree: u64,
    pub pgactivate: u64,
    pub pgdeactivate: u64,
    pub pglazyfree: u64,
    pub pgfault: u64,
    pub pgmajfault: u64,
    pub pglazyfreed: u64,
    pub pgreuse: u64,
    pub pgscan_direct_throttle: u64,
    pub zone_reclaim_success: u64,
    pub zone_reclaim_failed: u64,
    pub pginodesteal: u64,
    pub slabs_scanned: u64,
    pub kswapd_inodesteal: u64,
    pub kswapd_low_wmark_hit_quickly: u64,
    pub kswapd_high_wmark_hit_quickly: u64,
    pub pageoutrun: u64,
    pub pgrotated: u64,
    pub drop_pagecache: u64,
    pub drop_slab: u64,
    pub oom_kill: u64,
    pub numa_pte_updates: u64,
    pub numa_huge_pte_updates: u64,
    pub numa_hint_faults: u64,
    pub numa_hint_faults_local: u64,
    pub numa_pages_migrated: u64,
    pub pgmigrate_success: u64,
    pub pgmigrate_fail: u64,
    pub thp_migration_success: u64,
    pub thp_migration_fail: u64,
    pub thp_migration_split: u64,
    pub compact_migrate_scanned: u64,
    pub compact_free_scanned: u64,
    pub compact_isolated: u64,
    pub compact_stall: u64,
    pub compact_fail: u64,
    pub compact_success: u64,
    pub compact_daemon_wake: u64,
    pub compact_daemon_migrate_scanned: u64,
    pub compact_daemon_free_scanned: u64,
    pub htlb_buddy_alloc_success: u64,
    pub htlb_buddy_alloc_fail: u64,
    pub cma_alloc_success: u64,
    pub cma_alloc_fail: u64,
    pub unevictable_pgs_culled: u64,
    pub unevictable_pgs_scanned: u64,
    pub unevictable_pgs_rescued: u64,
    pub unevictable_pgs_mlocked: u64,
    pub unevictable_pgs_munlocked: u64,
    pub unevictable_pgs_cleared: u64,
    pub unevictable_pgs_stranded: u64,
    pub thp_fault_alloc: u64,
    pub thp_fault_fallback: u64,
    pub thp_fault_fallback_charge: u64,
    pub thp_collapse_alloc: u64,
    pub thp_collapse_alloc_failed: u64,
    pub thp_file_alloc: u64,
    pub thp_file_fallback: u64,
    pub thp_file_fallback_charge: u64,
    pub thp_file_mapped: u64,
    pub thp_split_page: u64,
    pub thp_split_page_failed: u64,
    pub thp_deferred_split_page: u64,
    pub thp_underused_split_page: u64,
    pub thp_split_pmd: u64,
    pub thp_scan_exceed_none_pte: u64,
    pub thp_scan_exceed_swap_pte: u64,
    pub thp_scan_exceed_share_pte: u64,
    pub thp_split_pud: u64,
    pub thp_zero_page_alloc: u64,
    pub thp_zero_page_alloc_failed: u64,
    pub thp_swpout: u64,
    pub thp_swpout_fallback: u64,
    pub balloon_inflate: u64,
    pub balloon_deflate: u64,
    pub balloon_migrate: u64,
    pub swap_ra: u64,
    pub swap_ra_hit: u64,
    pub swpin_zero: u64,
    pub swpout_zero: u64,
    pub ksm_swpin_copy: u64,
    pub cow_ksm: u64,
    pub zswpin: u64,
    pub zswpout: u64,
    pub zswpwb: u64,
    pub direct_map_level2_splits: u64,
    pub direct_map_level3_splits: u64,
    pub direct_map_level2_collapses: u64,
    pub direct_map_level3_collapses: u64,
    pub nr_unstable: u64,
}

impl ProcFSVmStatReader {
    pub fn new(
        path: &str,
        is_cachable: bool,
        is_root: bool,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self {
            reader: ProcFileReader::new(path, is_cachable, is_root)?,
            values: ProcVmStatFields::default(),
        })
    }

    pub fn read_and_parse(&mut self, field_filter: &HashMap<usize, bool>) -> bool {
        let read_status = self.reader.read();
        if read_status {
            self.parse_buffer(&field_filter);
        }
        read_status
    }

    pub fn values(&self) -> &ProcVmStatFields {
        &self.values
    }

    fn set_field(&mut self, field: usize, start: usize, end: usize) {
        let Some(bytes) = self.reader.buffer.get(start..end) else {
            return;
        };
        // Find the whitespace separating the field name from its value.
        let Some(mut value_start) = bytes.iter().position(|byte| byte.is_ascii_whitespace()) else {
            // This can happen if the buffer ends in the middle of a line.
            return;
        };
        // Skip all whitespace between the field name and value.
        while value_start < bytes.len() && bytes[value_start].is_ascii_whitespace() {
            value_start += 1;
        }
        if value_start == bytes.len() {
            return;
        }
        // Only include the contiguous decimal value.
        let mut value_end = value_start;
        while value_end < bytes.len() && bytes[value_end].is_ascii_digit() {
            value_end += 1;
        }
        if value_start == value_end {
            return;
        }
        let value = parse_u64_swar(&bytes[value_start..value_end]).unwrap_or_default();
        match field {
            1 => self.values.nr_free_pages = value,
            2 => self.values.nr_free_pages_blocks = value,
            3 => self.values.nr_zone_inactive_anon = value,
            4 => self.values.nr_zone_active_anon = value,
            5 => self.values.nr_zone_inactive_file = value,
            6 => self.values.nr_zone_active_file = value,
            7 => self.values.nr_zone_unevictable = value,
            8 => self.values.nr_zone_write_pending = value,
            9 => self.values.nr_mlock = value,
            10 => self.values.nr_zspages = value,
            11 => self.values.nr_free_cma = value,
            12 => self.values.nr_unaccepted = value,
            13 => self.values.numa_hit = value,
            14 => self.values.numa_miss = value,
            15 => self.values.numa_foreign = value,
            16 => self.values.numa_interleave = value,
            17 => self.values.numa_local = value,
            18 => self.values.numa_other = value,
            19 => self.values.nr_inactive_anon = value,
            20 => self.values.nr_active_anon = value,
            21 => self.values.nr_inactive_file = value,
            22 => self.values.nr_active_file = value,
            23 => self.values.nr_unevictable = value,
            24 => self.values.nr_slab_reclaimable = value,
            25 => self.values.nr_slab_unreclaimable = value,
            26 => self.values.nr_isolated_anon = value,
            27 => self.values.nr_isolated_file = value,
            28 => self.values.workingset_nodes = value,
            29 => self.values.workingset_refault_anon = value,
            30 => self.values.workingset_refault_file = value,
            31 => self.values.workingset_activate_anon = value,
            32 => self.values.workingset_activate_file = value,
            33 => self.values.workingset_restore_anon = value,
            34 => self.values.workingset_restore_file = value,
            35 => self.values.workingset_nodereclaim = value,
            36 => self.values.nr_anon_pages = value,
            37 => self.values.nr_mapped = value,
            38 => self.values.nr_file_pages = value,
            39 => self.values.nr_dirty = value,
            40 => self.values.nr_writeback = value,
            41 => self.values.nr_shmem = value,
            42 => self.values.nr_shmem_hugepages = value,
            43 => self.values.nr_shmem_pmdmapped = value,
            44 => self.values.nr_file_hugepages = value,
            45 => self.values.nr_file_pmdmapped = value,
            46 => self.values.nr_anon_transparent_hugepages = value,
            47 => self.values.nr_vmscan_write = value,
            48 => self.values.nr_vmscan_immediate_reclaim = value,
            49 => self.values.nr_dirtied = value,
            50 => self.values.nr_written = value,
            51 => self.values.nr_throttled_written = value,
            52 => self.values.nr_kernel_misc_reclaimable = value,
            53 => self.values.nr_foll_pin_acquired = value,
            54 => self.values.nr_foll_pin_released = value,
            55 => self.values.nr_vmalloc = value,
            56 => self.values.nr_kernel_stack = value,
            57 => self.values.nr_page_table_pages = value,
            58 => self.values.nr_sec_page_table_pages = value,
            59 => self.values.nr_iommu_pages = value,
            60 => self.values.nr_swapcached = value,
            61 => self.values.pgpromote_success = value,
            62 => self.values.pgpromote_candidate = value,
            63 => self.values.pgpromote_candidate_nrl = value,
            64 => self.values.pgdemote_kswapd = value,
            65 => self.values.pgdemote_direct = value,
            66 => self.values.pgdemote_khugepaged = value,
            67 => self.values.pgdemote_proactive = value,
            68 => self.values.pgsteal_kswapd = value,
            69 => self.values.pgsteal_direct = value,
            70 => self.values.pgsteal_khugepaged = value,
            71 => self.values.pgsteal_proactive = value,
            72 => self.values.pgsteal_anon = value,
            73 => self.values.pgsteal_file = value,
            74 => self.values.pgscan_kswapd = value,
            75 => self.values.pgscan_direct = value,
            76 => self.values.pgscan_khugepaged = value,
            77 => self.values.pgscan_proactive = value,
            78 => self.values.pgscan_anon = value,
            79 => self.values.pgscan_file = value,
            80 => self.values.pgrefill = value,
            81 => self.values.nr_hugetlb = value,
            82 => self.values.nr_balloon_pages = value,
            83 => self.values.nr_kernel_file_pages = value,
            84 => self.values.nr_gpu_active = value,
            85 => self.values.nr_gpu_reclaim = value,
            86 => self.values.nr_dirty_threshold = value,
            87 => self.values.nr_dirty_background_threshold = value,
            88 => self.values.nr_memmap_pages = value,
            89 => self.values.nr_memmap_boot_pages = value,
            90 => self.values.pgpgin = value,
            91 => self.values.pgpgout = value,
            92 => self.values.pswpin = value,
            93 => self.values.pswpout = value,
            94 => self.values.pgalloc_dma = value,
            95 => self.values.pgalloc_dma32 = value,
            96 => self.values.pgalloc_normal = value,
            97 => self.values.pgalloc_movable = value,
            98 => self.values.pgalloc_device = value,
            99 => self.values.allocstall_dma = value,
            100 => self.values.allocstall_dma32 = value,
            101 => self.values.allocstall_normal = value,
            102 => self.values.allocstall_movable = value,
            103 => self.values.allocstall_device = value,
            104 => self.values.pgskip_dma = value,
            105 => self.values.pgskip_dma32 = value,
            106 => self.values.pgskip_normal = value,
            107 => self.values.pgskip_movable = value,
            108 => self.values.pgskip_device = value,
            109 => self.values.pgfree = value,
            110 => self.values.pgactivate = value,
            111 => self.values.pgdeactivate = value,
            112 => self.values.pglazyfree = value,
            113 => self.values.pgfault = value,
            114 => self.values.pgmajfault = value,
            115 => self.values.pglazyfreed = value,
            116 => self.values.pgreuse = value,
            117 => self.values.pgscan_direct_throttle = value,
            118 => self.values.zone_reclaim_success = value,
            119 => self.values.zone_reclaim_failed = value,
            120 => self.values.pginodesteal = value,
            121 => self.values.slabs_scanned = value,
            122 => self.values.kswapd_inodesteal = value,
            123 => self.values.kswapd_low_wmark_hit_quickly = value,
            124 => self.values.kswapd_high_wmark_hit_quickly = value,
            125 => self.values.pageoutrun = value,
            126 => self.values.pgrotated = value,
            127 => self.values.drop_pagecache = value,
            128 => self.values.drop_slab = value,
            129 => self.values.oom_kill = value,
            130 => self.values.numa_pte_updates = value,
            131 => self.values.numa_huge_pte_updates = value,
            132 => self.values.numa_hint_faults = value,
            133 => self.values.numa_hint_faults_local = value,
            134 => self.values.numa_pages_migrated = value,
            135 => self.values.pgmigrate_success = value,
            136 => self.values.pgmigrate_fail = value,
            137 => self.values.thp_migration_success = value,
            138 => self.values.thp_migration_fail = value,
            139 => self.values.thp_migration_split = value,
            140 => self.values.compact_migrate_scanned = value,
            141 => self.values.compact_free_scanned = value,
            142 => self.values.compact_isolated = value,
            143 => self.values.compact_stall = value,
            144 => self.values.compact_fail = value,
            145 => self.values.compact_success = value,
            146 => self.values.compact_daemon_wake = value,
            147 => self.values.compact_daemon_migrate_scanned = value,
            148 => self.values.compact_daemon_free_scanned = value,
            149 => self.values.htlb_buddy_alloc_success = value,
            150 => self.values.htlb_buddy_alloc_fail = value,
            151 => self.values.cma_alloc_success = value,
            152 => self.values.cma_alloc_fail = value,
            153 => self.values.unevictable_pgs_culled = value,
            154 => self.values.unevictable_pgs_scanned = value,
            155 => self.values.unevictable_pgs_rescued = value,
            156 => self.values.unevictable_pgs_mlocked = value,
            157 => self.values.unevictable_pgs_munlocked = value,
            158 => self.values.unevictable_pgs_cleared = value,
            159 => self.values.unevictable_pgs_stranded = value,
            160 => self.values.thp_fault_alloc = value,
            161 => self.values.thp_fault_fallback = value,
            162 => self.values.thp_fault_fallback_charge = value,
            163 => self.values.thp_collapse_alloc = value,
            164 => self.values.thp_collapse_alloc_failed = value,
            165 => self.values.thp_file_alloc = value,
            166 => self.values.thp_file_fallback = value,
            167 => self.values.thp_file_fallback_charge = value,
            168 => self.values.thp_file_mapped = value,
            169 => self.values.thp_split_page = value,
            170 => self.values.thp_split_page_failed = value,
            171 => self.values.thp_deferred_split_page = value,
            172 => self.values.thp_underused_split_page = value,
            173 => self.values.thp_split_pmd = value,
            174 => self.values.thp_scan_exceed_none_pte = value,
            175 => self.values.thp_scan_exceed_swap_pte = value,
            176 => self.values.thp_scan_exceed_share_pte = value,
            177 => self.values.thp_split_pud = value,
            178 => self.values.thp_zero_page_alloc = value,
            179 => self.values.thp_zero_page_alloc_failed = value,
            180 => self.values.thp_swpout = value,
            181 => self.values.thp_swpout_fallback = value,
            182 => self.values.balloon_inflate = value,
            183 => self.values.balloon_deflate = value,
            184 => self.values.balloon_migrate = value,
            185 => self.values.swap_ra = value,
            186 => self.values.swap_ra_hit = value,
            187 => self.values.swpin_zero = value,
            188 => self.values.swpout_zero = value,
            189 => self.values.ksm_swpin_copy = value,
            190 => self.values.cow_ksm = value,
            191 => self.values.zswpin = value,
            192 => self.values.zswpout = value,
            193 => self.values.zswpwb = value,
            194 => self.values.direct_map_level2_splits = value,
            195 => self.values.direct_map_level3_splits = value,
            196 => self.values.direct_map_level2_collapses = value,
            197 => self.values.direct_map_level3_collapses = value,
            198 => self.values.nr_unstable = value,
            _ => {}
        }
    }

    fn parse_buffer(&mut self, field_filter: &HashMap<usize, bool>) {
        let mut field = 0usize;
        let mut start: Option<usize> = None;

        for i in 0..self.reader.buffer_len {
            let byte = self.reader.buffer[i];

            if byte == b'\n' || byte == b'\0' {
                if let Some(s) = start.take() {
                    field += 1;
                    if field_filter.get(&field).copied().unwrap_or(false) {
                        self.set_field(field, s, i);
                    }
                }
            } else if start.is_none() {
                start = Some(i);
            }
        }

        if let Some(s) = start {
            field += 1;
            if field_filter.get(&field).copied().unwrap_or(false) {
                self.set_field(field, s, self.reader.buffer_len);
            }
        }
    }
}

pub fn parse_procfs_vmstat(
    signal_hook: Arc<AtomicBool>,
    monitoring_heartbeat: u64,
    is_cachable: bool,
    is_root: bool,
) -> JoinHandle<()> {
    let load_avg_path = Path::new(PROC_FS_ROOT_PATH).join("vmstat");
    let load_avg_temp_reader =
        ProcFSVmStatReader::new(&load_avg_path.to_str().unwrap(), is_cachable, is_root);
    let mut load_avg_reader = match load_avg_temp_reader {
        Ok(reader) => Box::new(reader),
        Err(e) => panic!("Failed to create loadavg reader: {}", e),
    };
    let filter_map = HashMap::from([
        (1, true),
        (2, true),
        (3, true),
        (4, true),
        (5, true),
        (6, true),
        (7, true),
        (8, true),
        (9, true),
        (10, true),
        (11, true),
        (12, true),
        (13, true),
        (14, true),
        (15, true),
        (16, true),
        (17, true),
        (18, true),
        (19, true),
        (20, true),
        (21, true),
        (22, true),
        (23, true),
        (24, true),
        (25, true),
        (26, true),
        (27, true),
        (28, true),
        (29, true),
        (30, true),
        (31, true),
        (32, true),
        (33, true),
        (34, true),
        (35, true),
        (36, true),
        (37, true),
        (38, true),
        (39, true),
        (40, true),
        (41, true),
        (42, true),
        (43, true),
        (44, true),
        (45, true),
        (46, true),
        (47, true),
        (48, true),
        (49, true),
        (50, true),
        (51, true),
        (52, true),
        (53, true),
        (54, true),
        (55, true),
        (56, true),
        (57, true),
        (58, true),
        (59, true),
        (60, true),
        (61, true),
        (62, true),
        (63, true),
        (64, true),
        (65, true),
        (66, true),
        (67, true),
        (68, true),
        (69, true),
        (70, true),
        (71, true),
        (72, true),
        (73, true),
        (74, true),
        (75, true),
        (76, true),
        (77, true),
        (78, true),
        (79, true),
        (80, true),
        (81, true),
        (82, true),
        (83, true),
        (84, true),
        (85, true),
        (86, true),
        (87, true),
        (88, true),
        (89, true),
        (90, true),
        (91, true),
        (92, true),
        (93, true),
        (94, true),
        (95, true),
        (96, true),
        (97, true),
        (98, true),
        (99, true),
        (100, true),
        (101, true),
        (102, true),
        (103, true),
        (104, true),
        (105, true),
        (106, true),
        (107, true),
        (108, true),
        (109, true),
        (110, true),
        (111, true),
        (112, true),
        (113, true),
        (114, true),
        (115, true),
        (116, true),
        (117, true),
        (118, true),
        (119, true),
        (120, true),
        (121, true),
        (122, true),
        (123, true),
        (124, true),
        (125, true),
        (126, true),
        (127, true),
        (128, true),
        (129, true),
        (130, true),
        (131, true),
        (132, true),
        (133, true),
        (134, true),
        (135, true),
        (136, true),
        (137, true),
        (138, true),
        (139, true),
        (140, true),
        (141, true),
        (142, true),
        (143, true),
        (144, true),
        (145, true),
        (146, true),
        (147, true),
        (148, true),
        (149, true),
        (150, true),
        (151, true),
        (152, true),
        (153, true),
        (154, true),
        (155, true),
        (156, true),
        (157, true),
        (158, true),
        (159, true),
        (160, true),
        (161, true),
        (162, true),
        (163, true),
        (164, true),
        (165, true),
        (166, true),
        (167, true),
        (168, true),
        (169, true),
        (170, true),
        (171, true),
        (172, true),
        (173, true),
        (174, true),
        (175, true),
        (176, true),
        (177, true),
        (178, true),
        (179, true),
        (180, true),
        (181, true),
        (182, true),
        (183, true),
        (184, true),
        (185, true),
        (186, true),
        (187, true),
        (188, true),
        (189, true),
        (190, true),
        (191, true),
        (192, true),
        (193, true),
        (194, true),
        (195, true),
        (196, true),
        (197, true),
        (198, true),
    ]);
    let thread_handle = thread::spawn(move || {
        while !signal_hook.load(Ordering::Relaxed) {
            let read_status = load_avg_reader.read_and_parse(&filter_map);
            if !read_status {
                println!("Failed to read loadavg, ProcFS File closed!");
                break;
            }
            println!("Parsed: {:?}", load_avg_reader.values());
            println!("=====================================");
            thread::sleep(std::time::Duration::from_millis(monitoring_heartbeat));
        }
        println!("Killed LoadAvg thread!!");
    });
    thread_handle
}
