use serde::Deserialize;
use std::collections::HashMap;

#[derive(Debug, Default, Deserialize)]
pub struct ProcPidfsStatConfig {
    pub pid: bool,
    pub comm: bool,
    pub state: bool,
    pub ppid: bool,
    pub pgrp: bool,
    pub session: bool,
    pub tty_nr: bool,
    pub tpgid: bool,
    pub flags: bool,
    pub minflt: bool,
    pub cminflt: bool,
    pub majflt: bool,
    pub cmajflt: bool,
    pub utime: bool,
    pub stime: bool,
    pub cutime: bool,
    pub cstime: bool,
    pub priority: bool,
    pub nice: bool,
    pub num_threads: bool,
    pub itrealvalue: bool,
    pub starttime: bool,
    pub vsize: bool,
    pub rss: bool,
    pub rsslim: bool,
    pub startcode: bool,
    pub endcode: bool,
    pub startstack: bool,
    pub kstkesp: bool,
    pub kstkeip: bool,
    pub signal: bool,
    pub blocked: bool,
    pub sigignore: bool,
    pub sigcatch: bool,
    pub wchan: bool,
    pub nswap: bool,
    pub cnswap: bool,
    pub exit_signal: bool,
    pub processor: bool,
    pub rt_priority: bool,
    pub policy: bool,
    pub delayacct_blkio_ticks: bool,
    pub guest_time: bool,
    pub cguest_time: bool,
    pub start_data: bool,
    pub end_data: bool,
    pub start_brk: bool,
    pub arg_start: bool,
    pub arg_end: bool,
    pub env_start: bool,
    pub env_end: bool,
    pub exit_code: bool,
}

impl ProcPidfsStatConfig {
    pub fn get_hashmap(&self) -> HashMap<usize, bool> {
        HashMap::from([
            (1, self.pid),
            (2, self.comm),
            (3, self.state),
            (4, self.ppid),
            (5, self.pgrp),
            (6, self.session),
            (7, self.tty_nr),
            (8, self.tpgid),
            (9, self.flags),
            (10, self.minflt),
            (11, self.cminflt),
            (12, self.majflt),
            (13, self.cmajflt),
            (14, self.utime),
            (15, self.stime),
            (16, self.cutime),
            (17, self.cstime),
            (18, self.priority),
            (19, self.nice),
            (20, self.num_threads),
            (21, self.itrealvalue),
            (22, self.starttime),
            (23, self.vsize),
            (24, self.rss),
            (25, self.rsslim),
            (26, self.startcode),
            (27, self.endcode),
            (28, self.startstack),
            (29, self.kstkesp),
            (30, self.kstkeip),
            (31, self.signal),
            (32, self.blocked),
            (33, self.sigignore),
            (34, self.sigcatch),
            (35, self.wchan),
            (36, self.nswap),
            (37, self.cnswap),
            (38, self.exit_signal),
            (39, self.processor),
            (40, self.rt_priority),
            (41, self.policy),
            (42, self.delayacct_blkio_ticks),
            (43, self.guest_time),
            (44, self.cguest_time),
            (45, self.start_data),
            (46, self.end_data),
            (47, self.start_brk),
            (48, self.arg_start),
            (49, self.arg_end),
            (50, self.env_start),
            (51, self.env_end),
            (52, self.exit_code),
        ])
    }
}
