use serde::Deserialize;
use std::collections::HashMap;

#[derive(Debug, Default, Deserialize)]
pub struct ProcMemInfoConfig {
    pub mem_total: bool,
    pub mem_free: bool,
    pub mem_available: bool,
    pub mem_buffers: bool,
    pub mem_cached: bool,
    pub mem_swap_cached: bool,

    pub mem_active: bool,
    pub mem_inactive: bool,
    pub mem_active_anon: bool,
    pub mem_inactive_anon: bool,
    pub mem_active_file: bool,
    pub mem_inactive_file: bool,
    pub mem_unevictable: bool,
    pub mem_mlocked: bool,

    pub mem_swap_total: bool,
    pub mem_swap_free: bool,
    pub mem_zswap: bool,
    pub mem_zswapped: bool,

    pub mem_dirty: bool,
    pub mem_write_back: bool,
    pub mem_anon_pages: bool,
    pub mem_mapped: bool,
    pub mem_shmem: bool,

    pub mem_k_reclaimable: bool,
    pub mem_slab: bool,
    pub mem_s_reclaimable: bool,
    pub mem_s_unreclaim: bool,

    pub mem_kernel_stack: bool,
    pub mem_page_tables: bool,
    pub mem_sec_page_tables: bool,

    pub mem_nfs_unstable: bool,
    pub mem_bounce: bool,
    pub mem_write_back_tmp: bool,

    pub mem_commit_limit: bool,
    pub mem_committed_as: bool,

    pub mem_vmalloc_total: bool,
    pub mem_vmalloc_used: bool,
    pub mem_vmalloc_chunk: bool,

    pub mem_percpu: bool,
    pub mem_hardware_corrupted: bool,

    pub mem_anon_huge_pages: bool,
    pub mem_shmem_huge_pages: bool,
    pub mem_shmem_pmd_mapped: bool,
    pub mem_file_huge_pages: bool,
    pub mem_file_pmd_mapped: bool,

    pub mem_cma_total: bool,
    pub mem_cma_free: bool,

    pub mem_unaccepted: bool,
    pub mem_balloon: bool,
    pub mem_gpu_active: bool,
    pub mem_gpu_reclaim: bool,

    pub mem_huge_pages_total: bool,
    pub mem_huge_pages_free: bool,
    pub mem_huge_pages_reserved: bool,
    pub mem_huge_pages_surp: bool,
    pub mem_huge_page_size: bool,
    pub mem_hugetlb: bool,

    pub mem_direct_map_4k: bool,
    pub mem_direct_map_2m: bool,
    pub mem_direct_map_1g: bool,
}

impl ProcMemInfoConfig {
    pub fn get_hashmap(&self) -> HashMap<usize, bool> {
        HashMap::from([
            (1, self.mem_total),
            (2, self.mem_free),
            (3, self.mem_available),
            (4, self.mem_buffers),
            (5, self.mem_cached),
            (6, self.mem_swap_cached),
            (7, self.mem_active),
            (8, self.mem_inactive),
            (9, self.mem_active_anon),
            (10, self.mem_inactive_anon),
            (11, self.mem_active_file),
            (12, self.mem_inactive_file),
            (13, self.mem_unevictable),
            (14, self.mem_mlocked),
            (15, self.mem_swap_total),
            (16, self.mem_swap_free),
            (17, self.mem_zswap),
            (18, self.mem_zswapped),
            (19, self.mem_dirty),
            (20, self.mem_write_back),
            (21, self.mem_anon_pages),
            (22, self.mem_mapped),
            (23, self.mem_shmem),
            (24, self.mem_k_reclaimable),
            (25, self.mem_slab),
            (26, self.mem_s_reclaimable),
            (27, self.mem_s_unreclaim),
            (28, self.mem_kernel_stack),
            (29, self.mem_page_tables),
            (30, self.mem_sec_page_tables),
            (31, self.mem_nfs_unstable),
            (32, self.mem_bounce),
            (33, self.mem_write_back_tmp),
            (34, self.mem_commit_limit),
            (35, self.mem_committed_as),
            (36, self.mem_vmalloc_total),
            (37, self.mem_vmalloc_used),
            (38, self.mem_vmalloc_chunk),
            (39, self.mem_percpu),
            (40, self.mem_hardware_corrupted),
            (41, self.mem_anon_huge_pages),
            (42, self.mem_shmem_huge_pages),
            (43, self.mem_shmem_pmd_mapped),
            (44, self.mem_file_huge_pages),
            (45, self.mem_file_pmd_mapped),
            (46, self.mem_cma_total),
            (47, self.mem_cma_free),
            (48, self.mem_unaccepted),
            (49, self.mem_balloon),
            (50, self.mem_gpu_active),
            (51, self.mem_gpu_reclaim),
            (52, self.mem_huge_pages_total),
            (53, self.mem_huge_pages_free),
            (54, self.mem_huge_pages_reserved),
            (55, self.mem_huge_pages_surp),
            (56, self.mem_huge_page_size),
            (57, self.mem_hugetlb),
            (58, self.mem_direct_map_4k),
            (59, self.mem_direct_map_2m),
            (60, self.mem_direct_map_1g),
        ])
    }

    pub fn get_field_string_to_struct_ids(&self) -> HashMap<&str, (usize, bool)> {
        HashMap::from([
            ("MemTotal", (1, self.mem_active)),
            ("MemFree", (2, self.mem_free)),
            ("MemAvailable", (3, self.mem_available)),
            ("Buffers", (4, self.mem_buffers)),
            ("Cached", (5, self.mem_cached)),
            ("SwapCached", (6, self.mem_swap_cached)),
            ("Active", (7, self.mem_active)),
            ("Inactive", (8, self.mem_inactive)),
            ("Active(anon)", (9, self.mem_active_anon)),
            ("Inactive(anon)", (10, self.mem_inactive_anon)),
            ("Active(file)", (11, self.mem_active_file)),
            ("Inactive(file)", (12, self.mem_inactive_file)),
            ("Unevictable", (13, self.mem_unevictable)),
            ("Mlocked", (14, self.mem_mlocked)),
            ("SwapTotal", (15, self.mem_swap_total)),
            ("SwapFree", (16, self.mem_swap_free)),
            ("Zswap", (17, self.mem_zswap)),
            ("Zswapped", (18, self.mem_zswapped)),
            ("Dirty", (19, self.mem_dirty)),
            ("Writeback", (20, self.mem_write_back)),
            ("AnonPages", (21, self.mem_anon_pages)),
            ("Mapped", (22, self.mem_mapped)),
            ("Shmem", (23, self.mem_shmem)),
            ("KReclaimable", (24, self.mem_k_reclaimable)),
            ("Slab", (25, self.mem_slab)),
            ("SReclaimable", (26, self.mem_s_reclaimable)),
            ("SUnreclaim", (27, self.mem_s_unreclaim)),
            ("KernelStack", (28, self.mem_kernel_stack)),
            ("PageTables", (29, self.mem_page_tables)),
            ("SecPageTables", (30, self.mem_sec_page_tables)),
            ("NFS_Unstable", (31, self.mem_nfs_unstable)),
            ("Bounce", (32, self.mem_bounce)),
            ("WritebackTmp", (33, self.mem_write_back_tmp)),
            ("CommitLimit", (34, self.mem_commit_limit)),
            ("Committed_AS", (35, self.mem_committed_as)),
            ("VmallocTotal", (36, self.mem_vmalloc_total)),
            ("VmallocUsed", (37, self.mem_vmalloc_used)),
            ("VmallocChunk", (38, self.mem_vmalloc_chunk)),
            ("Percpu", (39, self.mem_percpu)),
            ("HardwareCorrupted", (40, self.mem_hardware_corrupted)),
            ("AnonHugePages", (41, self.mem_anon_huge_pages)),
            ("ShmemHugePages", (42, self.mem_shmem_huge_pages)),
            ("ShmemPmdMapped", (43, self.mem_shmem_pmd_mapped)),
            ("FileHugePages", (44, self.mem_file_huge_pages)),
            ("FilePmdMapped", (45, self.mem_file_pmd_mapped)),
            ("CmaTotal", (46, self.mem_cma_total)),
            ("CmaFree", (47, self.mem_cma_free)),
            ("Unaccepted", (48, self.mem_unaccepted)),
            ("Balloon", (49, self.mem_balloon)),
            ("GPUActive", (50, self.mem_gpu_active)),
            ("GPUReclaim", (51, self.mem_gpu_reclaim)),
            ("HugePages_Total", (52, self.mem_huge_pages_total)),
            ("HugePages_Free", (53, self.mem_huge_pages_free)),
            ("HugePages_Rsvd", (54, self.mem_huge_pages_reserved)),
            ("HugePages_Surp", (55, self.mem_huge_pages_surp)),
            ("Hugepagesize", (56, self.mem_huge_page_size)),
            ("Hugetlb", (57, self.mem_hugetlb)),
            ("DirectMap4k", (58, self.mem_direct_map_4k)),
            ("DirectMap2M", (59, self.mem_direct_map_2m)),
            ("DirectMap1G", (60, self.mem_direct_map_1g)),
        ])
    }
}
