use serde::Deserialize;
use std::collections::HashMap;

// its the status config
// its from the /proc/<PID>/status

#[derive(Debug, Default, Deserialize)]
pub struct ProcPIDStatusConfig {
    pub name: bool,
    pub umask: bool,
    pub state: bool,
    pub tgid: bool,
    pub ngid: bool,
    pub pid: bool,
    pub ppid: bool,
    pub tracer_pid: bool,
    pub uid: bool,
    pub gid: bool,
    pub fd_size: bool,
    pub groups: bool,
    pub nstgid: bool,
    pub nspid: bool,
    pub nspgid: bool,
    pub nssid: bool,
    pub kthread: bool,
    pub vm_peak: bool,
    pub vm_size: bool,
    pub vm_lck: bool,
    pub vm_pin: bool,
    pub vm_hwm: bool,
    pub vm_rss: bool,
    pub rss_anon: bool,
    pub rss_file: bool,
    pub rss_shmem: bool,
    pub vm_data: bool,
    pub vm_stk: bool,
    pub vm_exe: bool,
    pub vm_lib: bool,
    pub vm_pte: bool,
    pub vm_swap: bool,
    pub hugetlb_pages: bool,
    pub core_dumping: bool,
    pub thp_enabled: bool,
    pub untag_mask: bool,
    pub threads: bool,
    pub sigq: bool,
    pub sigpnd: bool,
    pub shdpnd: bool,
    pub sigblk: bool,
    pub sigign: bool,
    pub sigcgt: bool,
    pub capinh: bool,
    pub capprm: bool,
    pub capeff: bool,
    pub capbnd: bool,
    pub capamb: bool,
    pub nonewprivs: bool,
    pub seccomp: bool,
    pub seccomp_filters: bool,
    pub speculation_store_bypass: bool,
    pub speculationindirectbranch: bool,
    pub cpus_allowed: bool,
    pub cpus_allowed_list: bool,
    pub mems_allowed: bool,
    pub mems_allowed_list: bool,
    pub voluntary_ctxt_switches: bool,
    pub nonvoluntary_ctxt_switches: bool,
    pub x86_thread_features: bool,
    pub x86_thread_features_locked: bool,
}

impl ProcPIDStatusConfig {
    pub fn get_hashmap(&self) -> HashMap<usize, bool> {
        HashMap::from([
            (1, self.name),
            (2, self.umask),
            (3, self.state),
            (4, self.tgid),
            (5, self.ngid),
            (6, self.pid),
            (7, self.ppid),
            (8, self.tracer_pid),
            (9, self.uid),
            (10, self.gid),
            (11, self.fd_size),
            (12, self.groups),
            (13, self.nstgid),
            (14, self.nspid),
            (15, self.nspgid),
            (16, self.nssid),
            (17, self.kthread),
            (18, self.vm_peak),
            (19, self.vm_size),
            (20, self.vm_lck),
            (21, self.vm_pin),
            (22, self.vm_hwm),
            (23, self.vm_rss),
            (24, self.rss_anon),
            (25, self.rss_file),
            (26, self.rss_shmem),
            (27, self.vm_data),
            (28, self.vm_stk),
            (29, self.vm_exe),
            (30, self.vm_lib),
            (31, self.vm_pte),
            (32, self.vm_swap),
            (33, self.hugetlb_pages),
            (34, self.core_dumping),
            (35, self.thp_enabled),
            (36, self.untag_mask),
            (37, self.threads),
            (38, self.sigq),
            (39, self.sigpnd),
            (40, self.shdpnd),
            (41, self.sigblk),
            (42, self.sigign),
            (43, self.sigcgt),
            (44, self.capinh),
            (45, self.capprm),
            (46, self.capeff),
            (47, self.capbnd),
            (48, self.capamb),
            (49, self.nonewprivs),
            (50, self.seccomp),
            (51, self.seccomp_filters),
            (52, self.speculation_store_bypass),
            (53, self.speculationindirectbranch),
            (54, self.cpus_allowed),
            (55, self.cpus_allowed_list),
            (56, self.mems_allowed),
            (57, self.mems_allowed_list),
            (58, self.voluntary_ctxt_switches),
            (59, self.nonvoluntary_ctxt_switches),
            (60, self.x86_thread_features),
            (61, self.x86_thread_features_locked),
        ])
    }

    pub fn get_field_string_to_struct_ids(&self) -> HashMap<&str, (usize, bool)> {
        HashMap::from([
            ("Name", (1, self.name)),
            ("Umask", (2, self.umask)),
            ("State", (3, self.state)),
            ("Tgid", (4, self.tgid)),
            ("Ngid", (5, self.ngid)),
            ("Pid", (6, self.pid)),
            ("PPid", (7, self.ppid)),
            ("TracerPid", (8, self.tracer_pid)),
            ("Uid", (9, self.uid)),
            ("Gid", (10, self.gid)),
            ("FDSize", (11, self.fd_size)),
            ("Groups", (12, self.groups)),
            ("NStgid", (13, self.nstgid)),
            ("NSpid", (14, self.nspid)),
            ("NSpgid", (15, self.nspgid)),
            ("NSsid", (16, self.nssid)),
            ("Kthread", (17, self.kthread)),
            ("VmPeak", (18, self.vm_peak)),
            ("VmSize", (19, self.vm_size)),
            ("VmLck", (20, self.vm_lck)),
            ("VmPin", (21, self.vm_pin)),
            ("VmHWM", (22, self.vm_hwm)),
            ("VmRSS", (23, self.vm_rss)),
            ("RssAnon", (24, self.rss_anon)),
            ("RssFile", (25, self.rss_file)),
            ("RssShmem", (26, self.rss_shmem)),
            ("VmData", (27, self.vm_data)),
            ("VmStk", (28, self.vm_stk)),
            ("VmExe", (29, self.vm_exe)),
            ("VmLib", (30, self.vm_lib)),
            ("VmPTE", (31, self.vm_pte)),
            ("VmSwap", (32, self.vm_swap)),
            ("HugetlbPages", (33, self.hugetlb_pages)),
            ("CoreDumping", (34, self.core_dumping)),
            ("THP_enabled", (35, self.thp_enabled)),
            ("untag_mask", (36, self.untag_mask)),
            ("Threads", (37, self.threads)),
            ("SigQ", (38, self.sigq)),
            ("SigPnd", (39, self.sigpnd)),
            ("ShdPnd", (40, self.shdpnd)),
            ("SigBlk", (41, self.sigblk)),
            ("SigIgn", (42, self.sigign)),
            ("SigCgt", (43, self.sigcgt)),
            ("CapInh", (44, self.capinh)),
            ("CapPrm", (45, self.capprm)),
            ("CapEff", (46, self.capeff)),
            ("CapBnd", (47, self.capbnd)),
            ("CapAmb", (48, self.capamb)),
            ("NoNewPrivs", (49, self.nonewprivs)),
            ("Seccomp", (50, self.seccomp)),
            ("Seccomp_filters", (51, self.seccomp_filters)),
            (
                "Speculation_Store_Bypass",
                (52, self.speculation_store_bypass),
            ),
            (
                "SpeculationIndirectBranch",
                (53, self.speculationindirectbranch),
            ),
            ("Cpus_allowed", (54, self.cpus_allowed)),
            ("Cpus_allowed_list", (55, self.cpus_allowed_list)),
            ("Mems_allowed", (56, self.mems_allowed)),
            ("Mems_allowed_list", (57, self.mems_allowed_list)),
            (
                "voluntary_ctxt_switches",
                (58, self.voluntary_ctxt_switches),
            ),
            (
                "nonvoluntary_ctxt_switches",
                (59, self.nonvoluntary_ctxt_switches),
            ),
            ("x86_Thread_features", (60, self.x86_thread_features)),
            (
                "x86_Thread_features_locked",
                (61, self.x86_thread_features_locked),
            ),
        ])
    }
}
