use serde::Deserialize;
use std::collections::HashMap;

// its the load avg config
// its from the /proc/loadavg

#[derive(Debug, Default, Deserialize)]
pub struct ProcLoadAvgConfig {
    pub nr_free_pages: bool,
    pub nr_free_pages_blocks: bool,
    pub nr_zone_inactive_anon: bool,
    pub nr_zone_active_anon: bool,
    pub nr_zone_inactive_file: bool,
    pub nr_zone_active_file: bool,
    pub nr_zone_unevictable: bool,
    pub nr_zone_write_pending: bool,
    pub nr_mlock: bool,
    pub nr_zspages: bool,
    pub nr_free_cma: bool,
    pub nr_unaccepted: bool,
    pub numa_hit: bool,
    pub numa_miss: bool,
    pub numa_foreign: bool,
    pub numa_interleave: bool,
    pub numa_local: bool,
    pub numa_other: bool,
    pub nr_inactive_anon: bool,
    pub nr_active_anon: bool,
    pub nr_inactive_file: bool,
    pub nr_active_file: bool,
    pub nr_unevictable: bool,
    pub nr_slab_reclaimable: bool,
    pub nr_slab_unreclaimable: bool,
    pub nr_isolated_anon: bool,
    pub nr_isolated_file: bool,
    pub workingset_nodes: bool,
    pub workingset_refault_anon: bool,
    pub workingset_refault_file: bool,
    pub workingset_activate_anon: bool,
    pub workingset_activate_file: bool,
    pub workingset_restore_anon: bool,
    pub workingset_restore_file: bool,
    pub workingset_nodereclaim: bool,
    pub nr_anon_pages: bool,
    pub nr_mapped: bool,
    pub nr_file_pages: bool,
    pub nr_dirty: bool,
    pub nr_writeback: bool,
    pub nr_shmem: bool,
    pub nr_shmem_hugepages: bool,
    pub nr_shmem_pmdmapped: bool,
    pub nr_file_hugepages: bool,
    pub nr_file_pmdmapped: bool,
    pub nr_anon_transparent_hugepages: bool,
    pub nr_vmscan_write: bool,
    pub nr_vmscan_immediate_reclaim: bool,
    pub nr_dirtied: bool,
    pub nr_written: bool,
    pub nr_throttled_written: bool,
    pub nr_kernel_misc_reclaimable: bool,
    pub nr_foll_pin_acquired: bool,
    pub nr_foll_pin_released: bool,
    pub nr_vmalloc: bool,
    pub nr_kernel_stack: bool,
    pub nr_page_table_pages: bool,
    pub nr_sec_page_table_pages: bool,
    pub nr_iommu_pages: bool,
    pub nr_swapcached: bool,
    pub pgpromote_success: bool,
    pub pgpromote_candidate: bool,
    pub pgpromote_candidate_nrl: bool,
    pub pgdemote_kswapd: bool,
    pub pgdemote_direct: bool,
    pub pgdemote_khugepaged: bool,
    pub pgdemote_proactive: bool,
    pub pgsteal_kswapd: bool,
    pub pgsteal_direct: bool,
    pub pgsteal_khugepaged: bool,
    pub pgsteal_proactive: bool,
    pub pgsteal_anon: bool,
    pub pgsteal_file: bool,
    pub pgscan_kswapd: bool,
    pub pgscan_direct: bool,
    pub pgscan_khugepaged: bool,
    pub pgscan_proactive: bool,
    pub pgscan_anon: bool,
    pub pgscan_file: bool,
    pub pgrefill: bool,
    pub nr_hugetlb: bool,
    pub nr_balloon_pages: bool,
    pub nr_kernel_file_pages: bool,
    pub nr_gpu_active: bool,
    pub nr_gpu_reclaim: bool,
    pub nr_dirty_threshold: bool,
    pub nr_dirty_background_threshold: bool,
    pub nr_memmap_pages: bool,
    pub nr_memmap_boot_pages: bool,
    pub pgpgin: bool,
    pub pgpgout: bool,
    pub pswpin: bool,
    pub pswpout: bool,
    pub pgalloc_dma: bool,
    pub pgalloc_dma32: bool,
    pub pgalloc_normal: bool,
    pub pgalloc_movable: bool,
    pub pgalloc_device: bool,
    pub allocstall_dma: bool,
    pub allocstall_dma32: bool,
    pub allocstall_normal: bool,
    pub allocstall_movable: bool,
    pub allocstall_device: bool,
    pub pgskip_dma: bool,
    pub pgskip_dma32: bool,
    pub pgskip_normal: bool,
    pub pgskip_movable: bool,
    pub pgskip_device: bool,
    pub pgfree: bool,
    pub pgactivate: bool,
    pub pgdeactivate: bool,
    pub pglazyfree: bool,
    pub pgfault: bool,
    pub pgmajfault: bool,
    pub pglazyfreed: bool,
    pub pgreuse: bool,
    pub pgscan_direct_throttle: bool,
    pub zone_reclaim_success: bool,
    pub zone_reclaim_failed: bool,
    pub pginodesteal: bool,
    pub slabs_scanned: bool,
    pub kswapd_inodesteal: bool,
    pub kswapd_low_wmark_hit_quickly: bool,
    pub kswapd_high_wmark_hit_quickly: bool,
    pub pageoutrun: bool,
    pub pgrotated: bool,
    pub drop_pagecache: bool,
    pub drop_slab: bool,
    pub oom_kill: bool,
    pub numa_pte_updates: bool,
    pub numa_huge_pte_updates: bool,
    pub numa_hint_faults: bool,
    pub numa_hint_faults_local: bool,
    pub numa_pages_migrated: bool,
    pub pgmigrate_success: bool,
    pub pgmigrate_fail: bool,
    pub thp_migration_success: bool,
    pub thp_migration_fail: bool,
    pub thp_migration_split: bool,
    pub compact_migrate_scanned: bool,
    pub compact_free_scanned: bool,
    pub compact_isolated: bool,
    pub compact_stall: bool,
    pub compact_fail: bool,
    pub compact_success: bool,
    pub compact_daemon_wake: bool,
    pub compact_daemon_migrate_scanned: bool,
    pub compact_daemon_free_scanned: bool,
    pub htlb_buddy_alloc_success: bool,
    pub htlb_buddy_alloc_fail: bool,
    pub cma_alloc_success: bool,
    pub cma_alloc_fail: bool,
    pub unevictable_pgs_culled: bool,
    pub unevictable_pgs_scanned: bool,
    pub unevictable_pgs_rescued: bool,
    pub unevictable_pgs_mlocked: bool,
    pub unevictable_pgs_munlocked: bool,
    pub unevictable_pgs_cleared: bool,
    pub unevictable_pgs_stranded: bool,
    pub thp_fault_alloc: bool,
    pub thp_fault_fallback: bool,
    pub thp_fault_fallback_charge: bool,
    pub thp_collapse_alloc: bool,
    pub thp_collapse_alloc_failed: bool,
    pub thp_file_alloc: bool,
    pub thp_file_fallback: bool,
    pub thp_file_fallback_charge: bool,
    pub thp_file_mapped: bool,
    pub thp_split_page: bool,
    pub thp_split_page_failed: bool,
    pub thp_deferred_split_page: bool,
    pub thp_underused_split_page: bool,
    pub thp_split_pmd: bool,
    pub thp_scan_exceed_none_pte: bool,
    pub thp_scan_exceed_swap_pte: bool,
    pub thp_scan_exceed_share_pte: bool,
    pub thp_split_pud: bool,
    pub thp_zero_page_alloc: bool,
    pub thp_zero_page_alloc_failed: bool,
    pub thp_swpout: bool,
    pub thp_swpout_fallback: bool,
    pub balloon_inflate: bool,
    pub balloon_deflate: bool,
    pub balloon_migrate: bool,
    pub swap_ra: bool,
    pub swap_ra_hit: bool,
    pub swpin_zero: bool,
    pub swpout_zero: bool,
    pub ksm_swpin_copy: bool,
    pub cow_ksm: bool,
    pub zswpin: bool,
    pub zswpout: bool,
    pub zswpwb: bool,
    pub direct_map_level2_splits: bool,
    pub direct_map_level3_splits: bool,
    pub direct_map_level2_collapses: bool,
    pub direct_map_level3_collapses: bool,
    pub nr_unstable: bool,
}

impl ProcLoadAvgConfig {
    pub fn get_hashmap(&self) -> HashMap<usize, bool> {
        HashMap::from([
            (1, self.nr_free_pages),
            (2, self.nr_free_pages_blocks),
            (3, self.nr_zone_inactive_anon),
            (4, self.nr_zone_active_anon),
            (5, self.nr_zone_inactive_file),
            (6, self.nr_zone_active_file),
            (7, self.nr_zone_unevictable),
            (8, self.nr_zone_write_pending),
            (9, self.nr_mlock),
            (10, self.nr_zspages),
            (11, self.nr_free_cma),
            (12, self.nr_unaccepted),
            (13, self.numa_hit),
            (14, self.numa_miss),
            (15, self.numa_foreign),
            (16, self.numa_interleave),
            (17, self.numa_local),
            (18, self.numa_other),
            (19, self.nr_inactive_anon),
            (20, self.nr_active_anon),
            (21, self.nr_inactive_file),
            (22, self.nr_active_file),
            (23, self.nr_unevictable),
            (24, self.nr_slab_reclaimable),
            (25, self.nr_slab_unreclaimable),
            (26, self.nr_isolated_anon),
            (27, self.nr_isolated_file),
            (28, self.workingset_nodes),
            (29, self.workingset_refault_anon),
            (30, self.workingset_refault_file),
            (31, self.workingset_activate_anon),
            (32, self.workingset_activate_file),
            (33, self.workingset_restore_anon),
            (34, self.workingset_restore_file),
            (35, self.workingset_nodereclaim),
            (36, self.nr_anon_pages),
            (37, self.nr_mapped),
            (38, self.nr_file_pages),
            (39, self.nr_dirty),
            (40, self.nr_writeback),
            (41, self.nr_shmem),
            (42, self.nr_shmem_hugepages),
            (43, self.nr_shmem_pmdmapped),
            (44, self.nr_file_hugepages),
            (45, self.nr_file_pmdmapped),
            (46, self.nr_anon_transparent_hugepages),
            (47, self.nr_vmscan_write),
            (48, self.nr_vmscan_immediate_reclaim),
            (49, self.nr_dirtied),
            (50, self.nr_written),
            (51, self.nr_throttled_written),
            (52, self.nr_kernel_misc_reclaimable),
            (53, self.nr_foll_pin_acquired),
            (54, self.nr_foll_pin_released),
            (55, self.nr_vmalloc),
            (56, self.nr_kernel_stack),
            (57, self.nr_page_table_pages),
            (58, self.nr_sec_page_table_pages),
            (59, self.nr_iommu_pages),
            (60, self.nr_swapcached),
            (61, self.pgpromote_success),
            (62, self.pgpromote_candidate),
            (63, self.pgpromote_candidate_nrl),
            (64, self.pgdemote_kswapd),
            (65, self.pgdemote_direct),
            (66, self.pgdemote_khugepaged),
            (67, self.pgdemote_proactive),
            (68, self.pgsteal_kswapd),
            (69, self.pgsteal_direct),
            (70, self.pgsteal_khugepaged),
            (71, self.pgsteal_proactive),
            (72, self.pgsteal_anon),
            (73, self.pgsteal_file),
            (74, self.pgscan_kswapd),
            (75, self.pgscan_direct),
            (76, self.pgscan_khugepaged),
            (77, self.pgscan_proactive),
            (78, self.pgscan_anon),
            (79, self.pgscan_file),
            (80, self.pgrefill),
            (81, self.nr_hugetlb),
            (82, self.nr_balloon_pages),
            (83, self.nr_kernel_file_pages),
            (84, self.nr_gpu_active),
            (85, self.nr_gpu_reclaim),
            (86, self.nr_dirty_threshold),
            (87, self.nr_dirty_background_threshold),
            (88, self.nr_memmap_pages),
            (89, self.nr_memmap_boot_pages),
            (90, self.pgpgin),
            (91, self.pgpgout),
            (92, self.pswpin),
            (93, self.pswpout),
            (94, self.pgalloc_dma),
            (95, self.pgalloc_dma32),
            (96, self.pgalloc_normal),
            (97, self.pgalloc_movable),
            (98, self.pgalloc_device),
            (99, self.allocstall_dma),
            (100, self.allocstall_dma32),
            (101, self.allocstall_normal),
            (102, self.allocstall_movable),
            (103, self.allocstall_device),
            (104, self.pgskip_dma),
            (105, self.pgskip_dma32),
            (106, self.pgskip_normal),
            (107, self.pgskip_movable),
            (108, self.pgskip_device),
            (109, self.pgfree),
            (110, self.pgactivate),
            (111, self.pgdeactivate),
            (112, self.pglazyfree),
            (113, self.pgfault),
            (114, self.pgmajfault),
            (115, self.pglazyfreed),
            (116, self.pgreuse),
            (117, self.pgscan_direct_throttle),
            (118, self.zone_reclaim_success),
            (119, self.zone_reclaim_failed),
            (120, self.pginodesteal),
            (121, self.slabs_scanned),
            (122, self.kswapd_inodesteal),
            (123, self.kswapd_low_wmark_hit_quickly),
            (124, self.kswapd_high_wmark_hit_quickly),
            (125, self.pageoutrun),
            (126, self.pgrotated),
            (127, self.drop_pagecache),
            (128, self.drop_slab),
            (129, self.oom_kill),
            (130, self.numa_pte_updates),
            (131, self.numa_huge_pte_updates),
            (132, self.numa_hint_faults),
            (133, self.numa_hint_faults_local),
            (134, self.numa_pages_migrated),
            (135, self.pgmigrate_success),
            (136, self.pgmigrate_fail),
            (137, self.thp_migration_success),
            (138, self.thp_migration_fail),
            (139, self.thp_migration_split),
            (140, self.compact_migrate_scanned),
            (141, self.compact_free_scanned),
            (142, self.compact_isolated),
            (143, self.compact_stall),
            (144, self.compact_fail),
            (145, self.compact_success),
            (146, self.compact_daemon_wake),
            (147, self.compact_daemon_migrate_scanned),
            (148, self.compact_daemon_free_scanned),
            (149, self.htlb_buddy_alloc_success),
            (150, self.htlb_buddy_alloc_fail),
            (151, self.cma_alloc_success),
            (152, self.cma_alloc_fail),
            (153, self.unevictable_pgs_culled),
            (154, self.unevictable_pgs_scanned),
            (155, self.unevictable_pgs_rescued),
            (156, self.unevictable_pgs_mlocked),
            (157, self.unevictable_pgs_munlocked),
            (158, self.unevictable_pgs_cleared),
            (159, self.unevictable_pgs_stranded),
            (160, self.thp_fault_alloc),
            (161, self.thp_fault_fallback),
            (162, self.thp_fault_fallback_charge),
            (163, self.thp_collapse_alloc),
            (164, self.thp_collapse_alloc_failed),
            (165, self.thp_file_alloc),
            (166, self.thp_file_fallback),
            (167, self.thp_file_fallback_charge),
            (168, self.thp_file_mapped),
            (169, self.thp_split_page),
            (170, self.thp_split_page_failed),
            (171, self.thp_deferred_split_page),
            (172, self.thp_underused_split_page),
            (173, self.thp_split_pmd),
            (174, self.thp_scan_exceed_none_pte),
            (175, self.thp_scan_exceed_swap_pte),
            (176, self.thp_scan_exceed_share_pte),
            (177, self.thp_split_pud),
            (178, self.thp_zero_page_alloc),
            (179, self.thp_zero_page_alloc_failed),
            (180, self.thp_swpout),
            (181, self.thp_swpout_fallback),
            (182, self.balloon_inflate),
            (183, self.balloon_deflate),
            (184, self.balloon_migrate),
            (185, self.swap_ra),
            (186, self.swap_ra_hit),
            (187, self.swpin_zero),
            (188, self.swpout_zero),
            (189, self.ksm_swpin_copy),
            (190, self.cow_ksm),
            (191, self.zswpin),
            (192, self.zswpout),
            (193, self.zswpwb),
            (194, self.direct_map_level2_splits),
            (195, self.direct_map_level3_splits),
            (196, self.direct_map_level2_collapses),
            (197, self.direct_map_level3_collapses),
            (198, self.nr_unstable),
        ])
    }

    pub fn get_field_string_to_struct_ids(&self) -> HashMap<&str, (usize, bool)> {
        HashMap::from([
            ("nr_free_pages", (1, self.nr_free_pages)),
            ("nr_free_pages_blocks", (2, self.nr_free_pages_blocks)),
            ("nr_zone_inactive_anon", (3, self.nr_zone_inactive_anon)),
            ("nr_zone_active_anon", (4, self.nr_zone_active_anon)),
            ("nr_zone_inactive_file", (5, self.nr_zone_inactive_file)),
            ("nr_zone_active_file", (6, self.nr_zone_active_file)),
            ("nr_zone_unevictable", (7, self.nr_zone_unevictable)),
            ("nr_zone_write_pending", (8, self.nr_zone_write_pending)),
            ("nr_mlock", (9, self.nr_mlock)),
            ("nr_zspages", (10, self.nr_zspages)),
            ("nr_free_cma", (11, self.nr_free_cma)),
            ("nr_unaccepted", (12, self.nr_unaccepted)),
            ("numa_hit", (13, self.numa_hit)),
            ("numa_miss", (14, self.numa_miss)),
            ("numa_foreign", (15, self.numa_foreign)),
            ("numa_interleave", (16, self.numa_interleave)),
            ("numa_local", (17, self.numa_local)),
            ("numa_other", (18, self.numa_other)),
            ("nr_inactive_anon", (19, self.nr_inactive_anon)),
            ("nr_active_anon", (20, self.nr_active_anon)),
            ("nr_inactive_file", (21, self.nr_inactive_file)),
            ("nr_active_file", (22, self.nr_active_file)),
            ("nr_unevictable", (23, self.nr_unevictable)),
            ("nr_slab_reclaimable", (24, self.nr_slab_reclaimable)),
            ("nr_slab_unreclaimable", (25, self.nr_slab_unreclaimable)),
            ("nr_isolated_anon", (26, self.nr_isolated_anon)),
            ("nr_isolated_file", (27, self.nr_isolated_file)),
            ("workingset_nodes", (28, self.workingset_nodes)),
            ("workingset_refault_anon", (29, self.workingset_refault_anon)),
            ("workingset_refault_file", (30, self.workingset_refault_file)),
            (
                "workingset_activate_anon",
                (31, self.workingset_activate_anon),
            ),
            (
                "workingset_activate_file",
                (32, self.workingset_activate_file),
            ),
            ("workingset_restore_anon", (33, self.workingset_restore_anon)),
            ("workingset_restore_file", (34, self.workingset_restore_file)),
            ("workingset_nodereclaim", (35, self.workingset_nodereclaim)),
            ("nr_anon_pages", (36, self.nr_anon_pages)),
            ("nr_mapped", (37, self.nr_mapped)),
            ("nr_file_pages", (38, self.nr_file_pages)),
            ("nr_dirty", (39, self.nr_dirty)),
            ("nr_writeback", (40, self.nr_writeback)),
            ("nr_shmem", (41, self.nr_shmem)),
            ("nr_shmem_hugepages", (42, self.nr_shmem_hugepages)),
            ("nr_shmem_pmdmapped", (43, self.nr_shmem_pmdmapped)),
            ("nr_file_hugepages", (44, self.nr_file_hugepages)),
            ("nr_file_pmdmapped", (45, self.nr_file_pmdmapped)),
            (
                "nr_anon_transparent_hugepages",
                (46, self.nr_anon_transparent_hugepages),
            ),
            ("nr_vmscan_write", (47, self.nr_vmscan_write)),
            (
                "nr_vmscan_immediate_reclaim",
                (48, self.nr_vmscan_immediate_reclaim),
            ),
            ("nr_dirtied", (49, self.nr_dirtied)),
            ("nr_written", (50, self.nr_written)),
            ("nr_throttled_written", (51, self.nr_throttled_written)),
            (
                "nr_kernel_misc_reclaimable",
                (52, self.nr_kernel_misc_reclaimable),
            ),
            ("nr_foll_pin_acquired", (53, self.nr_foll_pin_acquired)),
            ("nr_foll_pin_released", (54, self.nr_foll_pin_released)),
            ("nr_vmalloc", (55, self.nr_vmalloc)),
            ("nr_kernel_stack", (56, self.nr_kernel_stack)),
            ("nr_page_table_pages", (57, self.nr_page_table_pages)),
            ("nr_sec_page_table_pages", (58, self.nr_sec_page_table_pages)),
            ("nr_iommu_pages", (59, self.nr_iommu_pages)),
            ("nr_swapcached", (60, self.nr_swapcached)),
            ("pgpromote_success", (61, self.pgpromote_success)),
            ("pgpromote_candidate", (62, self.pgpromote_candidate)),
            ("pgpromote_candidate_nrl", (63, self.pgpromote_candidate_nrl)),
            ("pgdemote_kswapd", (64, self.pgdemote_kswapd)),
            ("pgdemote_direct", (65, self.pgdemote_direct)),
            ("pgdemote_khugepaged", (66, self.pgdemote_khugepaged)),
            ("pgdemote_proactive", (67, self.pgdemote_proactive)),
            ("pgsteal_kswapd", (68, self.pgsteal_kswapd)),
            ("pgsteal_direct", (69, self.pgsteal_direct)),
            ("pgsteal_khugepaged", (70, self.pgsteal_khugepaged)),
            ("pgsteal_proactive", (71, self.pgsteal_proactive)),
            ("pgsteal_anon", (72, self.pgsteal_anon)),
            ("pgsteal_file", (73, self.pgsteal_file)),
            ("pgscan_kswapd", (74, self.pgscan_kswapd)),
            ("pgscan_direct", (75, self.pgscan_direct)),
            ("pgscan_khugepaged", (76, self.pgscan_khugepaged)),
            ("pgscan_proactive", (77, self.pgscan_proactive)),
            ("pgscan_anon", (78, self.pgscan_anon)),
            ("pgscan_file", (79, self.pgscan_file)),
            ("pgrefill", (80, self.pgrefill)),
            ("nr_hugetlb", (81, self.nr_hugetlb)),
            ("nr_balloon_pages", (82, self.nr_balloon_pages)),
            ("nr_kernel_file_pages", (83, self.nr_kernel_file_pages)),
            ("nr_gpu_active", (84, self.nr_gpu_active)),
            ("nr_gpu_reclaim", (85, self.nr_gpu_reclaim)),
            ("nr_dirty_threshold", (86, self.nr_dirty_threshold)),
            (
                "nr_dirty_background_threshold",
                (87, self.nr_dirty_background_threshold),
            ),
            ("nr_memmap_pages", (88, self.nr_memmap_pages)),
            ("nr_memmap_boot_pages", (89, self.nr_memmap_boot_pages)),
            ("pgpgin", (90, self.pgpgin)),
            ("pgpgout", (91, self.pgpgout)),
            ("pswpin", (92, self.pswpin)),
            ("pswpout", (93, self.pswpout)),
            ("pgalloc_dma", (94, self.pgalloc_dma)),
            ("pgalloc_dma32", (95, self.pgalloc_dma32)),
            ("pgalloc_normal", (96, self.pgalloc_normal)),
            ("pgalloc_movable", (97, self.pgalloc_movable)),
            ("pgalloc_device", (98, self.pgalloc_device)),
            ("allocstall_dma", (99, self.allocstall_dma)),
            ("allocstall_dma32", (100, self.allocstall_dma32)),
            ("allocstall_normal", (101, self.allocstall_normal)),
            ("allocstall_movable", (102, self.allocstall_movable)),
            ("allocstall_device", (103, self.allocstall_device)),
            ("pgskip_dma", (104, self.pgskip_dma)),
            ("pgskip_dma32", (105, self.pgskip_dma32)),
            ("pgskip_normal", (106, self.pgskip_normal)),
            ("pgskip_movable", (107, self.pgskip_movable)),
            ("pgskip_device", (108, self.pgskip_device)),
            ("pgfree", (109, self.pgfree)),
            ("pgactivate", (110, self.pgactivate)),
            ("pgdeactivate", (111, self.pgdeactivate)),
            ("pglazyfree", (112, self.pglazyfree)),
            ("pgfault", (113, self.pgfault)),
            ("pgmajfault", (114, self.pgmajfault)),
            ("pglazyfreed", (115, self.pglazyfreed)),
            ("pgreuse", (116, self.pgreuse)),
            ("pgscan_direct_throttle", (117, self.pgscan_direct_throttle)),
            ("zone_reclaim_success", (118, self.zone_reclaim_success)),
            ("zone_reclaim_failed", (119, self.zone_reclaim_failed)),
            ("pginodesteal", (120, self.pginodesteal)),
            ("slabs_scanned", (121, self.slabs_scanned)),
            ("kswapd_inodesteal", (122, self.kswapd_inodesteal)),
            (
                "kswapd_low_wmark_hit_quickly",
                (123, self.kswapd_low_wmark_hit_quickly),
            ),
            (
                "kswapd_high_wmark_hit_quickly",
                (124, self.kswapd_high_wmark_hit_quickly),
            ),
            ("pageoutrun", (125, self.pageoutrun)),
            ("pgrotated", (126, self.pgrotated)),
            ("drop_pagecache", (127, self.drop_pagecache)),
            ("drop_slab", (128, self.drop_slab)),
            ("oom_kill", (129, self.oom_kill)),
            ("numa_pte_updates", (130, self.numa_pte_updates)),
            ("numa_huge_pte_updates", (131, self.numa_huge_pte_updates)),
            ("numa_hint_faults", (132, self.numa_hint_faults)),
            ("numa_hint_faults_local", (133, self.numa_hint_faults_local)),
            ("numa_pages_migrated", (134, self.numa_pages_migrated)),
            ("pgmigrate_success", (135, self.pgmigrate_success)),
            ("pgmigrate_fail", (136, self.pgmigrate_fail)),
            ("thp_migration_success", (137, self.thp_migration_success)),
            ("thp_migration_fail", (138, self.thp_migration_fail)),
            ("thp_migration_split", (139, self.thp_migration_split)),
            ("compact_migrate_scanned", (140, self.compact_migrate_scanned)),
            ("compact_free_scanned", (141, self.compact_free_scanned)),
            ("compact_isolated", (142, self.compact_isolated)),
            ("compact_stall", (143, self.compact_stall)),
            ("compact_fail", (144, self.compact_fail)),
            ("compact_success", (145, self.compact_success)),
            ("compact_daemon_wake", (146, self.compact_daemon_wake)),
            (
                "compact_daemon_migrate_scanned",
                (147, self.compact_daemon_migrate_scanned),
            ),
            (
                "compact_daemon_free_scanned",
                (148, self.compact_daemon_free_scanned),
            ),
            (
                "htlb_buddy_alloc_success",
                (149, self.htlb_buddy_alloc_success),
            ),
            ("htlb_buddy_alloc_fail", (150, self.htlb_buddy_alloc_fail)),
            ("cma_alloc_success", (151, self.cma_alloc_success)),
            ("cma_alloc_fail", (152, self.cma_alloc_fail)),
            ("unevictable_pgs_culled", (153, self.unevictable_pgs_culled)),
            ("unevictable_pgs_scanned", (154, self.unevictable_pgs_scanned)),
            ("unevictable_pgs_rescued", (155, self.unevictable_pgs_rescued)),
            ("unevictable_pgs_mlocked", (156, self.unevictable_pgs_mlocked)),
            (
                "unevictable_pgs_munlocked",
                (157, self.unevictable_pgs_munlocked),
            ),
            ("unevictable_pgs_cleared", (158, self.unevictable_pgs_cleared)),
            (
                "unevictable_pgs_stranded",
                (159, self.unevictable_pgs_stranded),
            ),
            ("thp_fault_alloc", (160, self.thp_fault_alloc)),
            ("thp_fault_fallback", (161, self.thp_fault_fallback)),
            (
                "thp_fault_fallback_charge",
                (162, self.thp_fault_fallback_charge),
            ),
            ("thp_collapse_alloc", (163, self.thp_collapse_alloc)),
            (
                "thp_collapse_alloc_failed",
                (164, self.thp_collapse_alloc_failed),
            ),
            ("thp_file_alloc", (165, self.thp_file_alloc)),
            ("thp_file_fallback", (166, self.thp_file_fallback)),
            (
                "thp_file_fallback_charge",
                (167, self.thp_file_fallback_charge),
            ),
            ("thp_file_mapped", (168, self.thp_file_mapped)),
            ("thp_split_page", (169, self.thp_split_page)),
            ("thp_split_page_failed", (170, self.thp_split_page_failed)),
            ("thp_deferred_split_page", (171, self.thp_deferred_split_page)),
            (
                "thp_underused_split_page",
                (172, self.thp_underused_split_page),
            ),
            ("thp_split_pmd", (173, self.thp_split_pmd)),
            (
                "thp_scan_exceed_none_pte",
                (174, self.thp_scan_exceed_none_pte),
            ),
            (
                "thp_scan_exceed_swap_pte",
                (175, self.thp_scan_exceed_swap_pte),
            ),
            (
                "thp_scan_exceed_share_pte",
                (176, self.thp_scan_exceed_share_pte),
            ),
            ("thp_split_pud", (177, self.thp_split_pud)),
            ("thp_zero_page_alloc", (178, self.thp_zero_page_alloc)),
            (
                "thp_zero_page_alloc_failed",
                (179, self.thp_zero_page_alloc_failed),
            ),
            ("thp_swpout", (180, self.thp_swpout)),
            ("thp_swpout_fallback", (181, self.thp_swpout_fallback)),
            ("balloon_inflate", (182, self.balloon_inflate)),
            ("balloon_deflate", (183, self.balloon_deflate)),
            ("balloon_migrate", (184, self.balloon_migrate)),
            ("swap_ra", (185, self.swap_ra)),
            ("swap_ra_hit", (186, self.swap_ra_hit)),
            ("swpin_zero", (187, self.swpin_zero)),
            ("swpout_zero", (188, self.swpout_zero)),
            ("ksm_swpin_copy", (189, self.ksm_swpin_copy)),
            ("cow_ksm", (190, self.cow_ksm)),
            ("zswpin", (191, self.zswpin)),
            ("zswpout", (192, self.zswpout)),
            ("zswpwb", (193, self.zswpwb)),
            (
                "direct_map_level2_splits",
                (194, self.direct_map_level2_splits),
            ),
            (
                "direct_map_level3_splits",
                (195, self.direct_map_level3_splits),
            ),
            (
                "direct_map_level2_collapses",
                (196, self.direct_map_level2_collapses),
            ),
            (
                "direct_map_level3_collapses",
                (197, self.direct_map_level3_collapses),
            ),
            ("nr_unstable", (198, self.nr_unstable)),
        ])
    }
}
